apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dev
  labels:
    app: nginx
    profile: fargate
spec:
  selector:
    matchLabels:
      app: nginx
      profile: fargate
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        profile: fargate
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: dev
  labels:
    app: nginx
    profile: fargate
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30001
  selector:
    app: nginx
    profile: fargate
  type: LoadBalancer
